"""empty message

Revision ID: 34afb38e22e3
Revises: a6c2ccd5163c
Create Date: 2019-11-06 13:25:56.306750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34afb38e22e3'
down_revision = 'a6c2ccd5163c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'complete')
    # ### end Alembic commands ###
